# Generated by Django 2.1.3 on 2018-11-19 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfDisc_Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=10)),
                ('periodo', models.CharField(choices=[('MN', 'Matutino'), ('TD', 'Vesperino'), ('NT', 'Noturno')], default='NT', max_length=2)),
                ('DiscCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.Disc_Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Professor_Disc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.Professor')),
            ],
        ),
        migrations.AddField(
            model_name='profdisc_curso',
            name='profDisc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.Professor_Disc'),
        ),
    ]
