# Generated by Django 2.1.3 on 2018-11-21 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=4)),
                ('teoria', models.IntegerField()),
                ('pratica', models.IntegerField()),
                ('profDiscCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.ProfDisc_Curso')),
            ],
        ),
    ]
